import type { Message, SourceCitation } from '../types'
import type { ReactNode } from 'react'
import { formatRelativeTime } from '../utils/dateUtils'
import { trustedSourceUrl } from '../utils/chatThreads'

interface MessageBubbleProps {
  message: Message
  showAvatar: boolean
}

export function MessageBubble({ message, showAvatar }: MessageBubbleProps) {
  const isUser = message.role === 'user'
  const timeString = message.timestamp instanceof Date && !Number.isNaN(message.timestamp.getTime()) ? formatRelativeTime(message.timestamp) : 'just now'
  
  return (
    <div className={`flex gap-3 ${isUser ? 'justify-end' : 'justify-start'}`}>
      {!isUser && showAvatar && (
        <img className="message-avatar" src="/icons/icon-192.png" alt="Buglasan AI" />
      )}
      
      <div className={`max-w-[80%] ${isUser ? 'order-2' : 'order-1'}`}>
        <div
          className={`
            max-w-full break-words px-4 py-3 text-sm leading-7 whitespace-pre-wrap
            ${isUser
              ? 'rounded-2xl rounded-br-md bg-brand-blue text-white shadow-md shadow-blue-100'
              : 'rounded-2xl rounded-bl-md border border-slate-200/80 bg-white text-neutral-900 shadow-sm'
            }
          `}
        >
          {renderCitedContent(message.content, message.sources ?? [])}
        </div>
        
        <div className={`mt-1 flex items-center gap-1.5 text-[11px] text-neutral-400 ${isUser ? 'justify-end pr-1' : 'justify-start pl-1'}`}>
          <span>{timeString}</span>
        </div>
      </div>
      
      {isUser && showAvatar && (
        <div className="message-avatar user-avatar" aria-hidden="true">You</div>
      )}
    </div>
  )
}

export function renderCitedContent(content: unknown, sources: unknown) {
  const safeContent = typeof content === 'string' && content.trim() ? content : 'Unable to display this message.'
  const safeSources = Array.isArray(sources) ? sources.filter((source): source is SourceCitation => !!source && typeof source === 'object' && typeof source.id === 'string' && typeof source.title === 'string') : []
  const sourceById = new Map(safeSources.map((source) => [source.id, source]))
  const parts = safeContent.split(/(_\(src:\s*[a-zA-Z0-9_-]+\)_|\[Source\s+\d+\])/g)

  return parts.map((part, index) => {
    const idMatch = part.match(/^_\(src:\s*([a-zA-Z0-9_-]+)\)_$/)
    const numberMatch = part.match(/^\[Source\s+(\d+)\]$/)
    const source = idMatch
      ? sourceById.get(idMatch[1])
      : numberMatch
        ? safeSources[Number(numberMatch[1]) - 1]
        : undefined

    if (!source) return <span key={`${part}-${index}`}>{renderMarkdownText(part)}</span>
    return (
      <a
        key={`${source.id}-${index}`}
        href={trustedSourceUrl(source) ?? undefined}
        target="_blank"
        rel="noopener noreferrer"
        className="ml-1 inline-flex align-super text-xs font-semibold text-brand-blue underline-offset-2 hover:underline"
        aria-label={`Open source: ${source.title}`}
        title={source.title}
      >
        [{safeSources.indexOf(source) + 1}]
      </a>
    )
  })
}

/** Render the small Markdown subset generated by chat responses without parsing HTML. */
export function renderMarkdownText(text: string): ReactNode[] {
  return text.split(/(\*\*[^*]+\*\*|(?<!\*)\*[^*]+\*(?!\*))/g).map((part, index) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={index}>{renderSafeLinks(part.slice(2, -2), `bold-${index}`)}</strong>
    }
    if (part.startsWith('*') && part.endsWith('*')) {
      return <em key={index}>{renderSafeLinks(part.slice(1, -1), `italic-${index}`)}</em>
    }
    return renderSafeLinks(part, `text-${index}`)
  })
}

/** Render valid http(s) URLs as links without parsing or injecting HTML. */
export function renderSafeLinks(text: string, keyPrefix = 'url'): ReactNode | ReactNode[] {
  if (!/(https?:\/\/[^\s<]+)/.test(text)) return text
  return text.split(/(https?:\/\/[^\s<]+)/g).map((part, index) => {
    if (index % 2 === 0) return part
    const match = part.match(/^(.*?)([.,!?;:]+)?$/)
    const candidate = match?.[1] ?? part
    const punctuation = match?.[2] ?? ''
    if (!isSafeHttpUrl(candidate)) return part
    return <span key={`${keyPrefix}-${index}`}><a href={candidate} target="_blank" rel="noopener noreferrer" className="text-brand-blue underline underline-offset-2 hover:text-blue-800">{candidate}</a>{punctuation}</span>
  })
}

function isSafeHttpUrl(value: string): boolean {
  try {
    const url = new URL(value)
    return (url.protocol === 'http:' || url.protocol === 'https:') && !!url.hostname
  } catch {
    return false
  }
}
