import type { Message, SourceCitation } from '../types'
import type { ReactNode } from 'react'
import { formatRelativeTime } from '../utils/dateUtils'

interface MessageBubbleProps {
  message: Message
  festivalYear: number
  showAvatar: boolean
}

export function MessageBubble({ message, festivalYear, showAvatar }: MessageBubbleProps) {
  const isUser = message.role === 'user'
  const timeString = formatRelativeTime(message.timestamp)
  
  return (
    <div className={`flex gap-2 ${isUser ? 'justify-end' : 'justify-start'}`}>
      {!isUser && showAvatar && (
        <div className="flex-shrink-0 w-8 h-8 bg-fiesta-red rounded-full flex items-center justify-center text-white text-xs font-bold">
          🎭
        </div>
      )}
      
      <div className={`max-w-[80%] ${isUser ? 'order-2' : 'order-1'}`}>
        <div
          className={`
            px-4 py-2.5 rounded-2xl text-sm leading-relaxed whitespace-pre-wrap
            ${isUser
              ? 'bg-fiesta-red text-white rounded-br-md'
              : 'bg-white text-neutral-900 border border-neutral-200 rounded-bl-md shadow-sm'
            }
          `}
        >
          {renderCitedContent(message.content, message.sources ?? [])}
        </div>
        
        <div className={`flex items-center gap-1.5 mt-1 text-xs text-neutral-400 ${isUser ? 'justify-end pr-1' : 'justify-start pl-1'}`}>
          <span>{timeString}</span>
          {message.festivalYear && message.festivalYear !== festivalYear && (
            <span className="px-1.5 py-0.5 bg-fiesta-red-light text-fiesta-red rounded text-[10px] font-medium">
              FY {message.festivalYear}
            </span>
          )}
        </div>
      </div>
      
      {isUser && showAvatar && (
        <div className="flex-shrink-0 w-8 h-8 bg-fiesta-blue rounded-full flex items-center justify-center text-white text-xs font-bold">
          👤
        </div>
      )}
    </div>
  )
}

export function renderCitedContent(content: string, sources: SourceCitation[]) {
  const sourceById = new Map(sources.map((source) => [source.id, source]))
  const parts = content.split(/(_\(src:\s*[a-zA-Z0-9_-]+\)_|\[Source\s+\d+\])/g)

  return parts.map((part, index) => {
    const idMatch = part.match(/^_\(src:\s*([a-zA-Z0-9_-]+)\)_$/)
    const numberMatch = part.match(/^\[Source\s+(\d+)\]$/)
    const source = idMatch
      ? sourceById.get(idMatch[1])
      : numberMatch
        ? sources[Number(numberMatch[1]) - 1]
        : undefined

    if (!source) return <span key={`${part}-${index}`}>{renderMarkdownText(part)}</span>
    return (
      <a
        key={`${source.id}-${index}`}
        href={source.postUrl}
        target="_blank"
        rel="noopener noreferrer"
        className="ml-1 inline-flex align-super text-xs font-semibold text-fiesta-red underline-offset-2 hover:underline"
        aria-label={`Open source: ${source.title}`}
        title={source.title}
      >
        [{sources.indexOf(source) + 1}]
      </a>
    )
  })
}

/** Render the small Markdown subset generated by chat responses without parsing HTML. */
export function renderMarkdownText(text: string): ReactNode[] {
  return text.split(/(\*\*[^*]+\*\*|(?<!\*)\*[^*]+\*(?!\*))/g).map((part, index) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={index}>{part.slice(2, -2)}</strong>
    }
    if (part.startsWith('*') && part.endsWith('*')) {
      return <em key={index}>{part.slice(1, -1)}</em>
    }
    return part
  })
}
